apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: client
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
  type: {{ .Values.client.service.type }}