apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: mirmika/client:dev-latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          
