apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: mirmika/posts:dev-latest
          ports:
            - containerPort: 8001
            
