apiVersion: apps/v1
kind: Deployment
metadata:
  name: query
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
      - name: query
        image: mirmika/query:dev-latest
        ports:
        - containerPort: 8003
        
