namespace: staging
ingressClassName: nginx
host: stg.local
annotations:
  nginx.ingress.kubernetes.io/use-regex: "true"
paths:
  - path: /
    serviceName: client
    servicePort: 3000

  # Comments service
  - path: /posts/.*/comments
    pathType: ImplementationSpecific
    serviceName: comments
    servicePort: 8002
  - path: /comments-db
    pathType: ImplementationSpecific
    serviceName: comments
    servicePort: 8002

  # Posts service
  - path: /post/create
    serviceName: posts
    servicePort: 8001
  - path: /post
    serviceName: posts
    servicePort: 8001
  - path: /posts-db
    serviceName: posts
    servicePort: 8001

  # Query service
  - path: /posts
    serviceName: query
    servicePort: 8003
  - path: /query-db
    serviceName: query
    servicePort: 8003

  # Event-bus service
  - path: /events
    serviceName: event-bus
    servicePort: 8005
