# Kuma Uptime configuration placeholder
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: development
spec:
  type: NodePort
  selector:
    app: myapp  # Must match your deployment’s pod labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31080  # Fixed port between 30000-32767
