apiVersion: v1
kind: Service
metadata:
  name: client-nodeport-prod
  namespace: production
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31600
---
apiVersion: v1
kind: Service
metadata:
  name: comments-nodeport-prod
  namespace: production
spec:
  type: NodePort
  selector:
    app: comments
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 31201
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-nodeport-prod
  namespace: production
spec:
  type: NodePort
  selector:
    app: event-bus
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
      nodePort: 31202
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-nodeport-prod
  namespace: production
spec:
  type: NodePort
  selector:
    app: moderation
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
      nodePort: 31203
---
apiVersion: v1
kind: Service
metadata:
  name: post-nodeport-prod
  namespace: production
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 31204
---
apiVersion: v1
kind: Service
metadata:
  name: query-nodeport-prod
  namespace: production
spec:
  type: NodePort
  selector:
    app: query
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 31205
