apiVersion: v1
kind: Service
metadata:
  name: client-nodeport-stg
  namespace: staging
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31400
---
apiVersion: v1
kind: Service
metadata:
  name: comments-nodeport-stg
  namespace: staging
spec:
  type: NodePort
  selector:
    app: comments
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 31101
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-nodeport-stg
  namespace: staging
spec:
  type: NodePort
  selector:
    app: event-bus
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
      nodePort: 31102
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-nodeport-stg
  namespace: staging
spec:
  type: NodePort
  selector:
    app: moderation
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
      nodePort: 31103
---
apiVersion: v1
kind: Service
metadata:
  name: post-nodeport-stg
  namespace: staging
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 31104
---
apiVersion: v1
kind: Service
metadata:
  name: query-nodeport-stg
  namespace: staging
spec:
  type: NodePort
  selector:
    app: query
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 31105
