apiVersion: v1
kind: Service
metadata:
  name: comments
  namespace: development
spec:
  selector:
    app: comments
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
