apiVersion: v1
kind: Service
metadata:
  name: event-bus
  namespace: development
spec:
  selector:
    app: event-bus
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
  type: ClusterIP