apiVersion: v1
kind: Service
metadata:
  name: moderation
  namespace: development
spec:
  selector:
    app: moderation
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
  type: ClusterIP
