apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: event-bus
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
      annotations:                 
        kuma.io/sidecar-injection: enabled  
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
        - name: event-bus
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
