name: CD

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.1

      - name: Deploy to Dev
        run: bash scripts/deploy-dev.sh